- name: Install pipx
  ansible.builtin.apt:
    name:
      - pipx
    update_cache: true
    install_recommends: false

- name: Setup pipx for `user` user
  ansible.builtin.lineinfile:
    path: /home/user/.bashrc
    line: export PATH="$PATH:/home/user/.local/bin"

- name: Install ansible-core
  ansible.builtin.command: >
    /usr/bin/pipx install ansible-core
  register: result
  changed_when: "'''ansible-core'' already seems to be installed.' in result.stdout"
  become: true
  become_user: user
  become_flags: "-s"
