- name: Initialize controller
  hosts: controller
  become: true
  roles:
    - package
    - upload_files
    - install_ansible

- name: Miscellaneous settings
  hosts: all
  become: true
  roles:
    - misc
