- name: Add new groups
  ansible.builtin.group:
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    state: present
  with_items:
    - '{{ groups }}'

- name: Add new users
  ansible.builtin.user:
    name: '{{ item.name }}'
    uid: '{{ item.uid }}'
    group: '{{ item.name }}'
    shell: /bin/bash
    state: present
  with_items:
    - '{{ users }}'

- name: Set password
  ansible.builtin.user:
    name: '{{ item.name }}'
    password: "{{ item.password | password_hash('sha512', item.salt | default('')) }}"
    state: present
  with_items:
    - '{{ passwords }}'
  when:
    - item.password is defined
    - item.password != ''
  no_log: true

- name: Create .ssh directory
  ansible.builtin.file:
    path: /home/{{ item.name }}/.ssh/
    state: directory
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
    mode: 700
  with_items:
    - '{{ users }}'

- name: Set authorized_keys
  ansible.posix.authorized_key:
    user: '{{ item.name }}'
    state: present
    key: "{{ lookup('ansible.builtin.file', item.pubkey) }}"
  with_items:
    - '{{ users }}'
  when:
    - item.pubkey is defined

- name: Add to sudoers
  ansible.builtin.user:
    name: '{{ item.name }}'
    groups: sudo
    append: true
  with_items:
    - '{{ users }}'
  when:
    - item.sudoer
