- name: Remove `user` from sudo group
  ansible.builtin.user:
    name: user
    groups: ''
  when:
    - inventory_hostname == 'controller'

- name: Remove `user` from sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^user'
    state: absent
  when:
    - inventory_hostname == 'controller'

- name: Set hostname
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'
